### ISSUE TITLE
14F did not trigger bot

### ISSUE THREAD

**Issue by HadManySons** [HadManySons/AFSCbot#13]
https://www.reddit.com/r/AirForce/comments/6l04bq/afscbot_is_back_up_and_majorly_rewritten/djq61m6/

**Comment by pelletier2017** [comment]
I am building some tests and I'm not sure how exactly 14F didn't trigger. Looks like the bot replied to your comment but the other guy deleted his comment so I cant see it.

**Comment by HadManySons** [comment]
Yeah, I think it was possibly an exception that skipped commenting

**Comment by HadManySons** [comment]
So far a one time bug, going to close for now unless it reappears.
