### ISSUE TITLE
some strange AFSCs we can verify?

### ISSUE THREAD

**Issue by pelletier2017** [HadManySons/AFSCbot#16]
EnlistedAFSCs.csv:
8P100#Defense AttachÃ© line 152 
9A500#Temporarily Ineligible for Retraining â€“ Disqualified for Reasons Beyond Control line 165

OfficerShreds.csv:
lines 224-230 strange symbols
line 373 symbols should be apostrophe

Reason to bring it up is they throw errors when printing to console, but they also don't look like legit AFSC either.

**Comment by HadManySons** [comment]
They're legit. Those strange symbols are because they were copied from a wiki page in Unicode

**Comment by HadManySons** [comment]
Fixed
