### ISSUE TITLE
officer AFSC bug 16GB

### ISSUE THREAD

**Issue by pelletier2017** [HadManySons/AFSCbot#27]
https://www.reddit.com/r/AirForce/comments/6rdtll/deploying_to_incirlik_turkey/dl4dzly/?context=3

16GB ends up triggering 16G Air Force Operations Staff Officer. Maybe we can look into how the regex handles it. Something like 16Gs should work, but 16G(random caps letter) should not.

**Comment by HadManySons** [comment]
This is what happens when you refuse to standardize the way you write out your AFSC. 16GXB vs 16G1B vs 16GB etc..
