### ISSUE TITLE
Have AFSC bot check conversation for already defined AFSCs. 

### ISSUE THREAD

**Issue by Lex1020** [HadManySons/AFSCbot#32]
When having a conversation on reddit about certain AFSCs the bot goes crazy and responds to every comment even if it's the same AFSC already mentioned. It also seems to not have any concept of depth.

The bot should not respond every single time the same AFSC is mentioned in one comment thread. Have it respond once and then check of it's already responded in that thread before commenting again.

Responding every single time regardless of how deep the conversation goes just clutters everything.

**Comment by HadManySons** [comment]
I think I got this working in a test case. At least the checking every parent comment part. Just need to get it adapted to the AFSCbot now.

**Comment by HadManySons** [comment]
Feature coming in next commit. This was a good idea and a semi-fun challenge to figure out.
