### ISSUE TITLE
Officer AFSC Regex Error

### ISSUE THREAD

**Issue by aethros** [HadManySons/AFSCbot#33]
https://github.com/HadManySons/AFSCbot/blob/8844b31a92541dc48ddcade63747e641d84932d5/AFSCbot/process_comment.py#L5C51-L5C62

Officer AFSC Regex uses a Skill level of 0-9 (Odds), but that schema follows the enlisted skill table.

Officers have a skill position based upon the table below.
| Skill Level | Rating |
| --- | --- |
| 1 |  Entry |
| 2 |  Intermediate |
| 3 |  Qualified |
| 4 |  Staff |

**Comment by HadManySons** [comment]
You know, I never noticed that before. I will get this updated.

**Comment by aethros** [comment]
Pull request https://github.com/HadManySons/AFSCbot/pull/34 opened.

**Comment by HadManySons** [comment]
Any update to the changes requested in the PR?
